# Macro file for MPCEXsim
# 
# To be run preferably in batch, without graphics:
# % MPCEXsim[a,b] run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
/gps/verbose 2
/gps/particle gamma
/gps/ene/type Lin
/gps/ene/intercept 1
/gps/ene/gradient 0
/gps/ene/min 10.0 GeV
/gps/ene/max 10.0 GeV
#phi angle already defined
/gps/ang/rot1 -1 0 0
/gps/ang/type cos
/gps/ang/maxtheta 0.0737329 rad
/gps/ang/mintheta 0.0546339 rad
/run/beamOn 500
